root = "."
tmp_dir = "tmp"

[build]
cmd = "templ generate && go build -o ./tmp/main ."
bin = "./tmp/main"
include_ext = ["go", "templ"]
exclude_dir = ["tmp", "vendor", "node_modules"]
exclude_file = []
# Add this to ignore the generated files
exclude_regex = ["_templ\\.go$"]

[misc]
clean_on_exit = true
